# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
          index_name: app_%kernel.environment%
          types:
              faune:
                  properties:
                      family: ~
                      nameLatin: ~
                      vernacularName: {analyzer: french}
                      date: ~
                      department: ~
                  persistence:
                      driver: orm
                      model: App\Entity\Faune
                      provider: ~
                      finder: ~
          settings:
              index:
                  analysis:
                      analyzer:
                          french:
                              tokenizer: whitespace
                              filter:
                                  - asciifolding
                                  - lowercase
                                  - edge_nGram
                      filter:
                          edge_nGram:
                              type: edge_ngram
                              min_gram: 3
                              max_gram: 10
